site_name: pymata-cpx and FirmataCPx
markdown_extensions:
    - tables

nav:
      - Welcome: index.md
      - The Client Library and Host Firmware:
        - The pymata-cpx Client Library: client.md
        - The FirmataCPx Host Firmware: firmware.md
      - Usage:
        - The pymata-cpx API: callbacks.md
        - The Examples:
            - Buttons and Switches: buttons.md
            - Light Meter: light_meter.md
            - Servo: servo.md
            - The Clapper: clapper.md
            - The Tapper: tapper.md
            - Thermometer: temp.md
            - Tilted: accel.md
            - Touch Piano: touch.md



theme: 'windmill'
