site_name: pymata-cpx and FirmataCPx
markdown_extensions:
    - tables

nav:
      - Welcome: index.md
      - The Client Library and Host Firmware:
        - The pymata-cpx Client Library: client.md
        - The FirmataCPx Host Firmware: firmware.md
      - Usage:
        - The pymata-cpx API: callbacks.md
      - Need Help?: help.md



theme: 'windmill'
